### ISSUE TITLE
Add ignore list functionality to deactivate add-on on specific sites

### ISSUE THREAD

**Issue by AlexStrobel** [ufb/Textmarker#103]
It would be helpful to be able to define websites where the add-on should not show up when selecting text.
For example: I would like to add the website of my webmailer as "ignored" as I do not mark any text there ever, but the color pop up irritates me every time I select any text when composing an email.

Ways to ignore sites:
* "Exact" by writing the whole domain and page
* "(Sub)domain" by writing the (sub) domain
* "Placeholder" by using "*" for subdomains/pages 
* "RegEx" for nerds only

**Comment by ufb** [comment]
Hi @AlexStrobel 
This feature would be something for next year, since there is already so much on the todo list.
But for now you could make use of 2 settings:
1) Load Textmarker manually to ensure it's only active on pages you need it
2) Disable the highlighter popup and use an alternative highlight method (shortcut, context menu, highlight buttons in sidebar, automantic)

Here you find option 1)
![autoload](https://user-images.githubusercontent.com/17272252/76760399-e055f200-678d-11ea-8be0-7ae5ec243685.jpg)

2)
![marker-popup](https://user-images.githubusercontent.com/17272252/76760413-e6e46980-678d-11ea-9692-2a0e9bad319e.jpg)

Hope this helps!

**Comment by ufb** [comment]
Sorry, this is a wont-do, since it is too much work to accomplish this* and there is already the option 1 explained above which seems just fine for loading Textmarker only on pages you want it to.

*) The blacklist itself is not a big deal, it's more the iceberg underneath the surface.

This issue can be reopened if a lot of users would love having a blacklist and for some reason find it too much hassle to click on the button in the URL bar for loading Textmarker.
