### ISSUE TITLE
all Highlights are gone

### ISSUE THREAD

**Issue by gadia-aayush** [ufb/Textmarker#105]
@ufb , My Firefox was slow, so I Refreshed it and now I see that all my saved highlights are gone. Please help me to retrieve them all.

**Comment by ufb** [comment]
@gadia-aayush What do you mean by **"refreshed"**? Did you upgrade your Firefox version? Or did you restart Firefox? Or did you reload your tabs?
With **"saved highlights"** you mean you already had entries on Textmarker's history page and now they are gone?
Example history page:
![history](https://user-images.githubusercontent.com/17272252/78433244-f280cd00-7675-11ea-9847-907da246d2a8.jpg)

Since I don't know what happened (and how) best would be if you'd **e-mail me your Textmarker storage**. You can save/download your storage to a local file (.json format) and then e-mail me to undflybir@gmx.de
Then I would import it into my own Textmarker in order to get to the bottom of the problem ;-)

Here is how you download your storage:
![export](https://user-images.githubusercontent.com/17272252/78433996-31168780-7676-11ea-8adc-df9bfe50a5b2.jpg)

**Comment by gadia-aayush** [comment]
Hi,

Thanks for your reply. Yeah, I had *Restarted *my Firefox as it was running
slow. Sorry, to have mentioned that I refreshed it.

Well, I had entries on my Textmarker's history page prior to restarting my
Firefox but after the restart, I see no entries on my Textmarker's history
page. *Now, how to retrieve the entries that were present prior to the
restart ??*

I hope that the above explanation helps to explain my issue to you. I have
also attached both the Local & Synced Data with the email.
Looking forward to hearing from you.

Regards,
Aayush Gadia

**Comment by ufb** [comment]
I haven't received an email from you - also not in the junk folder.

**Comment by gadia-aayush** [comment]
Hi,

Thanks for your reply. Yeah, I had *Restarted *my Firefox as it was running
slow. Sorry, to have mentioned that I refreshed it.

Well, I had entries on my Textmarker's history page prior to restarting my
Firefox but after the restart, I see no entries on my Textmarker's history
page. *Now, how to retrieve the entries that were present prior to the
restart ??*

I hope that the above explanation helps to explain my issue to you. I have
also attached both the Local & Synced Data with the email.
Looking forward to hearing from you.

Regards,
Aayush Gadia

**Comment by ufb** [comment]
@gadia-aayush I haven't received an email from you - also not in the junk folder.
Please use above mentioned email address instead of replying to the auto-generated email from github ;-)

You can also inspect the .json files you downloaded yourself:
Check for this string: {"history":{"entries":{ -> is it followed by a closing curly bracket } or do you see your history entries in there? If not then they are lost - most likely to an irregular Firefox shutdown (crash?) -> unfortunately this can happen to Firefox local storages. Please create backups sometimes (such .json files you downloaded from the export page)

**Comment by gadia-aayush** [comment]
Thanks for your reply. Yeah, I checked my JSON File & it has no entries
inside the curly braces. I think it got lost due to the Firefox crash.
Thanks a lot for being so supportive.

Regards,

**Comment by ufb** [comment]
I'm sorry for the loss :(
Hopefully in the future Firefox can use a more reliable storage sysem - until then I recommend doing frequent backups.
Best wishes to you
