### ISSUE TITLE
Simpler Version

### ISSUE THREAD

**Issue by bytos** [ufb/Textmarker#107]
Is there a lite version of this addon?

I save pages with SingleFile addon and would like to highlight some text before and after saving, so need an addon to edit them later without issues.

I don't want addons that force you to use a server/index for later edits.

If all one needs is 'span style="background-color: #FFFF00"', why is it so hard to get just that functionality with some extra colors.

The web extension version of Page Hacker addon (old) no longer highlights text, and Amaya editor (old) would have been nice if it understood the single file web pages.

**Comment by ufb** [comment]
Hi @bytos 

> Is there a lite version of this addon?

No

> I save pages with SingleFile addon and would like to highlight some text before and after saving, so need an addon to edit them later without issues.

It won't work if you save highlights **before** and **after** (it's very technical to explain, but it's basically because Textmarker recognizes textmarks on a page that you don't have in your Textmarker history yet -> Textmarker identifies pages with highlights on by their URL and the page you saved with SingleFile obviously has a different URI than the original).
Make sure to first use SingleFile to save the website before using Textmarker on it.

> I don't want addons that force you to use a server/index for later edits.

Not sure what you mean by that. 1) Textmarker doesn't force you to anything at all. 2) Textmarker doesn't save anything to a server - but of course when you use Textmarker's save funcionality those highlights have to be saved somewhere -> Textmarker is using Firefox local simple-storage which is located in your Firefox profile folder on your computer.

> If all one needs is 'span style="background-color: #FFFF00"', why is it so hard to get just that functionality with some extra colors.

A simple highlighter that doesn't save your highlights would be a thousand times easier to program. There are some addons out there that do exactly that. So when you don't want your highlights to persist across page reloads then try [TextMarker Go](https://addons.mozilla.org/de/firefox/addon/textmarker-go/). I'm not sure what you mean by "why is it so hard": Obviously it's easier to build something that is easier. But I decided to not go with easy but building something better instead.

**Pro tip:** When you use Textmarker on pages you downloaded with SingleFile (**important:** make sure to first download the page before highlighting it if you want to save your highlights) you can take advantage of a Textmarker setting especially designed for use-cases like this where you can be sure that the page's content never gets altered (because you downloaded it):

![immut](https://user-images.githubusercontent.com/17272252/79492505-6466f800-8020-11ea-8395-07a72b111e18.jpg)

This setting will increase the reliability of a successful restoration of your saved hilights, because on "live" websites Textmarker has to assume that the website's (text)-content might have changed since your last visit and therefore it's very complicated to restore the highlights correctly - and of course even impossible if the corresponding text is not on the website anymore. With above setting enabled Textmarker will use a different algorithm for finding the correct text passages to hilight.

Hope this answer will help you
Best wishes

Pro

**Comment by bytos** [comment]
There's only one addon I know of, and found it today, that actually saves the highlights to the page, avoiding issues like the ones you mentioned.

It is Persistent Highlighter: "a watered-down [web extension] port of Prostetnic Highlighter".

It is old, but it will have to do for now.

**Comment by ufb** [comment]
> issues like the ones you mentioned

I did not mention any issues, just gave you some best-practice advice on how to use the addon

But I'm glad that you found something suited for you :) Be aware though that Persistent Highlighter is very buggy

**Comment by ufb** [comment]
> but almost all addons don't write to the file 

Actually making a website static/immutable (i.e. downloading it with SingeFile or any other equivalent tool) is the preferred way to use Textmarker since it assures that your highlights get restored in 100% of the cases (when using the above mentioned setting)
But of course Textmarker will not treat the online website the same as your downloaded version, because for Textmarker they are 2 different pages, since they have different URLs

Unfortunately there is not much out there for highlighting + saving the highlights. No "lite" addon anyway
