### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by DenB10** [ufb/Textmarker#11]
Hello,
It's a pleasure to use your already awesome add-on which contains more and more functionalities. Two suggestions though:
1) It's not easy to go to a specific highlight on a long page. It would be nice to have a way to jump between the highlights: a keyboard shortcut? buttons on the side of the page?
2) Is it possible to customize the sticky notes: more transparency with lost of focus? and, why not, color of the note background?
These are only suggestions, not fundamental, and I don't know if the implementation is possible...
Tschüs!
Denis

**Comment by ufb** [comment]
Hey Den,
2 (transparency): I could set them to opacity 0.75 (=transparency 0.25) on mouseout, this way a note would have 0 transparency when the mouse cursor is over it - what you think?
![note](https://user-images.githubusercontent.com/17272252/41560837-993f98d4-7348-11e8-975c-595cb0fc048e.PNG)

2 (colors): No big deal. I could display another button (under the delete- and minimize-buttons) with a gear, which opens a color palette with 5 colors.
All marks are stored as objects with different key-value-pairs like 'text', 'bookmarked', 'note', ... . Would be nice to save notes like this:
``note: {
  text: "text of note",
  color: "#hexhex"
}``, but now it's too late for that (if I want to avoid ugly case differentiation, because some users have already `note: "text of note"` in there storage), so I would go with ``note: "text of note", noteColor: "hexhex"`` - but seems fine to me.

1: Can you explain what you have in mind? You mean jumping from highlight to highlight to highlight... ? So, do you have trouble finding certain highlights or you just want to jump to the next highlight? Or having some anchors? Or more like the addon "TextMarker Go" is doing it - with arrow markers?

**Comment by DenB10** [comment]
1. I just would like a way to scroll through a long page to the desired highlight. I took a look at the "Textmarker Go" extension: arrow markers are a good idea. Another idea: a link in the history detail view to jump directly to the chosen highlight on the page.

2. Transparency: exactly that! Useful to see the text under the note.
Colors: not very important, only useful to better see a note on a colored page background.

**Comment by ufb** [comment]
I'll add the transparency (alongside your latest translations;-)) with next update.

At first, I didn't want to implement sticky notes, since it's too far away from the core functionality of the addon, but many users asked for it, because there isn't a good stand-alone addon for that, and it seems to be a popular feature. I still try to keep it simple, but a color option seems like a good idea to me, which is easy to add - probably with next update as well;)

About scrolling/jumping: These arrow markers of "TextMarker Go" look nice, but I tend not to clutter visited pages too much. I think I like your idea with adding a hashed link to each highlight in the detail view, but on the other hand you have to open this window first in order to "jump" to the desired highlight. I will put more thought into it and come up with a good solution - not for next update though, because I'm currently overworking code structure and another feature is already in the queue: WebDav support as alternative to FF syncing.

BTW: Thanks for the compliments on the addon and thanks for your help:)

**Comment by llagerlof** [comment]
A shortcut to jump between highlights would be useful. One key to "next" highlight, other key to "previous" highlight.

A nice usability feature would tell the user when he reached the last highlight with a small alert message (like vim does), so the user knowns that the "next highlight" keypress will return him to the first highlight. 

In the example below (vim editor), the text "search hit BOTTOM, continuing at TOP" only appears when the user finds the last ocurrence in search. The "next" keystroke will find the first one and the message disappear.

![2018-06-25 15_26_52-2 cygwin64 - _c_xampp_php](https://user-images.githubusercontent.com/193798/41868518-adf86f96-788c-11e8-8a28-92e8d614d450.png)

**Comment by ufb** [comment]
Do you have any shortcut suggestion? What do you think about [Ctrl] [Alt] [up] and [Ctrl] [Alt] [down] ?
Additionally I could display arrow buttons in the sidebar for usage without shortcuts.
Also, I tend to disable the "jump-highlights"-shortcut by default -> don't want to clutter the user's shortcut settings too much without explicit approval (via activation in Settings > Shortcuts).

**Comment by ufb** [comment]
Hey Den,
I'm going to publish 3.7.0 today or tomorrow.
There will be 8 colors for notes to choose from.
Transparency for non-active notes has to be enabled in the settings (misc).
"Jump"-controls probably with 3.8.0

**Comment by DenB10** [comment]
OK, thanks, well done!

**Comment by llagerlof** [comment]
[**@ufb**](https://github.com/ufb) commented on [25 de jun de 2018 17:35 BRT](https://github.com/ufb/Textmarker/issues/11#issuecomment-400086611 "2018-06-25T20:35:15Z - Replied by Github Reply Comments"):
> Do you have any shortcut suggestion? What do you think about [Ctrl] [Alt] [up] and [Ctrl] [Alt] [down] ?  
> 
> Additionally I could display arrow buttons in the sidebar for usage without shortcuts.  
> 
> Also, I tend to disable the "jump-highlights"-shortcut by default -&gt; don't want to clutter the user's shortcut settings too much without explicit approval (via activation in Settings &gt; Shortcuts).

Maybe "n" for next and "p" for previous? Set as default, but configurable. One of the many things I liked in your addon is the simplicity (like just "m" to mark).

**Comment by ufb** [comment]
Jump controls is done, will be released this week.
Decided to go for shortcuts [Alt]+[ArrowDown] and [Alt]+[ArrowUp] - find it more intuitive than [N] and [P].
This feature has to be activated in Settings>Shortcuts.
[Alt] can be changed to [Alt]+[Ctrl]; might add some additional shortcut options in future.
Navigationg thru highlights can also be accomplished via sidebar buttons.

@DenB10 I added a translation message (sb_h1b) - in case you wanna frenchify it before release ;) It's on branch `marknav`

**Comment by DenB10** [comment]
??? Is the branch updated? Because there is no new message available, the "sb_h1b" string is already translated!

**Comment by ufb** [comment]
yes, it's `"sb_h1b":{"message":"Use arrow keys to jump through your highlights ou cliquer sur un surlignage pour le sélectionner."},` on branch `marknav`:
[https://github.com/ufb/Textmarker/blob/marknav/extension/_locales/fr/messages.json](https://github.com/ufb/Textmarker/blob/marknav/extension/_locales/fr/messages.json) (line 381)

**Comment by DenB10** [comment]
OK, done! Excuse me, I looked in the master branch!

**Comment by ufb** [comment]
:)

**Comment by ufb** [comment]
Sorry, I forgot some wording -> h119, t119, t4212, t4213
it's on master branch already

**Comment by DenB10** [comment]
It even happens to the best :)
