### ISSUE TITLE
does not work in html off line

### ISSUE THREAD

**Issue by AleixaGan** [ufb/Textmarker#117]
I have installed the extension, but I work quite a bit with offline HTML.
But the extension does not work in offline files (that is, files that I have on the computer, and that I open to work).
I am a teacher, and I have many texts, articles, etc., on the computer, because where I live the internet connection is not very good ... the Brazilian hinterland!

**Comment by ufb** [comment]
Hi @AleixaGan 
The extension works offline, it is completely independent from internet connectivity.
Textmarker works for local files as long as you open them in your Firefox browser (URL would start with `file:///`)
This works for HTML, basic text files (.txt) and the like. PDF used to work too, but some years ago Firefox stopped extensions from working on their built-in PDF viewer.
Could you explain further what exactly it is you are trying? Do your local files end with the extension `.html`? Do you open them in Firefox?

**Comment by AleixaGan** [comment]
Well, now I see that one of the pages I have offline, if I access it online, textmarker doesn't work either.

http://www.stejeannedarc.net/
It doesn't work online, it doesn't work offline.

On my PC it is:
file: /// D: /JmJ_Biblioteca_bis/S%20Joanna%20d%20Arc/index.html

I wonder why?

On other offline pages, it actually works.

For example:
https://www.corpusthomisticum.org/iopera.html

which on my computer is:
file: /// C: /users/jimenez/JmJ_Biblioteca/S%20Tomas%20-%20Corpus%20Tomisticum/iOpera.html

What will be the problem with "stejeannedarc.net"?

Very grateful!

Translated by google

**Comment by ufb** [comment]
@AleixaGan 
Thank you for the feedback.
I checked above cited page "stejeannedarc". Did some highlights on it - both online and on a locally saved copy. Works fine for me.

> What will be the problem with "stejeannedarc.net"?

I cannot really tell without more details, because I wasn't able to reproduce any malfunctiong. What exactly doesn't work in your case? Highlighting in general? Or the restoration of your highlights on reload of the page? Or something else?
The best way for me to see what is going wrong is if you'd send me your history entry for the live/online page via email (undflybir@gmx.de). This way I could import it to my own Textmarker instance for testing.*

One (out of a million) possibilites is that you have mulltiple history entries for the same URL.

*) You can export a history entry like this:
Go to Textmarker's history page and click the download button next to the history enry for the online page of stejeannedarc. You'll be prompted to save the entry to a local .json file. This file will hold all information of this entry and can be imported to any Textmarker history (i.e. mine).

> Very grateful!

My pleasure!
