### ISSUE TITLE
Custom markers not importing-Firefox 74 Win 8.1

### ISSUE THREAD

**Issue by piecevcake** [ufb/Textmarker#123]
Followed your advice ro remove and reinstall textmarker after it has stopped working.

I had custom markers in the exported local settings json.  They have not been installed when I imported it.  Only the defaults are showing after import.

This is consistent behaviour on several profiles.  No import has restored custom markers in any profile.

**Comment by ufb** [comment]
Hi @piecevcake ,

> Followed your advice ro remove and reinstall textmarker after it has stopped working.

Did the reinstallation help?

> Only the defaults are showing after import.

> No import has restored custom markers in any profile.

Thank you for this bug report, I appreciate it! I'll add a note on my to-fix-list.

Btw: I've noted your review on the addon page. Please understand that I'm happy to help users realizing some feature requests and while I'm generally not minding much if someone gives 4 or 5 stars I don't really see why I should do someone a favor who was downvoting the extension (4 is lower than 4,5). I'm sure you didn't mean it as a "downvote", but a lot of users seem to think that giving less than 5 stars would somehow be a motivation for me to improve things - it's not;) quite the opposite, actually.

**Comment by piecevcake** [comment]
Thanks for your quick reply.  Now that I have found the support link I'll take it out of my review.

I see the same issue was raised in https://github.com/ufb/Textmarker/issues/122 .

In answer to your questions- 

I said in my report above that reinstall and re-import settings did NOT work.  Can you clarify your question "did it work?". 

5 stars is for perfectly working addons.  Not ones which have bugs and break.  Fix the bugs and I will happily change it.
You are not doing ME a "favour" by fixing bugs in your addon.  You are doing yourself a favour.  I am doing YOU a favour by taking the time to tell you about them where other people who try addons just vote with their feet.  (Uninstall or mark down.)

![textmarker custom markers gone after local data imported @2020 05 25, 08_34_44](https://user-images.githubusercontent.com/32110576/82764484-2224a800-9e63-11ea-83d8-911f76201964.png)

**Comment by ufb** [comment]
> I see the same issue was raised in #122 .

Oh, I wasn't sure what #122 was saying^^ Thanks for clarifications:)

> I said in my report above that reinstall and re-import settings did NOT work. Can you clarify your question "did it work?".

I understood that Textmarker wasn't working at all ("after it has stopped workin") and after reinstallation you couldn't import your settings. That's leaves the question open if - besides being unable to import your settings - Textmarker started working again. Sorry in case of a misunderstanding..

> 5 stars is for perfectly working addons. Not ones which have bugs and break. Fix the bugs and I will happily change it. ATM its a 2 because it keeps breaking and you have to set up the whole thing from scratch. 

WOW! While I'm always thankful for bug reports you were asking for several new features in your review. So, it's still unclear why I should spend my time implementing features you were asking for.
If you had read the review guidlines you'd know that reviews are not there for bug reports or feature requests - I cannot think of any reason why I should put all the work in giving you all those notes related features you were asking for. You seem to confuse me with a shop you bought a product from. I develop and maintain Textmarker open source and absolutely for free to give something to the community and not to please customers. Because you are not a customer - maybe you confuse me with some online shop you bought a product from..

**Comment by piecevcake** [comment]
https://github.com/ufb/Textmarker/issues/125

**Comment by piecevcake** [comment]
The markers seem to be in storage.js.migrated (if that is the correct place?
There is no other file in your addon folder

![phr-markers THERE storage js migrated - Notepad @2020 05 26, 08_17_39](https://user-images.githubusercontent.com/32110576/82842075-692aa000-9f2c-11ea-8b39-79ad3e35e99e.png)

**Comment by ufb** [comment]
I think you find Textmarker's storage here:
..\AppData\Roaming\Mozilla\Firefox\Profiles\<...>\storage\default\moz-extension+++<...>^userContextId=<...>\idb\<...>wleabcEoxlt-eengsairo.sqlite

**Comment by ufb** [comment]
Hint: You can retrieve Textmarker's storage on Firefox' `about:debugging` page:
Choose tab "This Firefox", look for Textmarker and click "Inspect" (or "Debug", not sure in English version). Then choose tab "Console" and enter the following in there:
`browser.storage.local.get(null).then(data => {console.log(JSON.stringify(data))});`
Hit enter. You'll get the local storage of Textmarker. For the synced storage replace `local` with `sync`.
[See also here for instructions](https://discourse.mozilla.org/t/migrating-extension-storage-local-data-to-a-new-profile-indexeddb-manually/37033)

**Comment by ufb** [comment]
Assuming that you are right and #122 is referring to the same issue
