### ISSUE TITLE
[feature] Show which highlights have a note attached / which highlight corresponds to a given note.

### ISSUE THREAD

**Issue by hmijail** [ufb/Textmarker#133]
**Is your feature request related to a problem? Please describe.**
I can't know whether/which one of my highlights have a note attached.

**Describe the solution you'd like**
I would like my note-carrying highlights to be, well, highlighted.

**Describe alternatives you've considered**
Maybe notes could be independent of the highlights; having a note in the margin by a paragraph can be meaningful enough. The current way seems to only allow me to highlight the whole paragraph for this. This makes smaller highlights less visible / makes them look less important.

The way PDF readers deal with notes (like Preview.app in macOS) is just like this: a note can be set anywhere in the page. Just like a real-life sticky note.

OurStickys is a great Firefox add-on that also works this way, and shows in the scroll bar where notes are.

**Comment by hmijail** [comment]
Of course this applies to notes which have been collapsed or moved from their highlight.

**Comment by hmijail** [comment]
Probably related: OurStickys can create and restore a note on a Google Docs page. 
But Textmarker fails because it needs a text selection to highlight and anchor the note, while Google Docs hijack the normal text selecting. So even if you manage to highlight text with Textmarker (for example in the filename in a GDocs page) and attach a note, on reload the highlight fails to load and so the note is missing.

**Comment by hmijail** [comment]
Similarly, given a note, it's hard to know which one is the related highlight.

**Comment by ufb** [comment]
Hi hmijail, thx for the post. A lot of text, but I'll go thru all of it;)

> I can't know whether/which one of my highlights have a note attached.

You can. There are several ways to tell:
![click-on-note](https://user-images.githubusercontent.com/17272252/84385023-300e5300-abef-11ea-8af1-dc90c9cfe278.jpg)
In sidebar:
![notes-display](https://user-images.githubusercontent.com/17272252/84385034-343a7080-abef-11ea-9f3d-f8b8e5db4646.jpg)

> I would like my note-carrying highlights to be, well, highlighted.

This issue is marked as duplicate - see here: #96 

> Maybe notes could be independent of the highlights; having a note in the margin by a paragraph can be meaningful enough. The current way seems to only allow me to highlight the whole paragraph for this. This makes smaller highlights less visible / makes them look less important.

You don't have to highlight the whole paragraph. But yes, sticky notes are bound to highlights. This is a highlighter extension after all;)
But you can move a note elsewhere, Textmarker will remember its offsets to top and left of the window.
There are also notes that are independent of highlights, but they only appear in the sidebar.

> The way PDF readers deal with notes (like Preview.app in macOS) is just like this: a note can be set anywhere in the page. Just like a real-life sticky note.
> 
> OurStickys is a great Firefox add-on that also works this way, and shows in the scroll bar where notes are.


> OurStickys can create and restore a note on a Google Docs page.

It seems to me the best option for sticky notes are extensions for sticky notes - i.e. OurStickys ;)

> Textmarker fails because it needs a text selection to highlight and anchor the note, while Google Docs hijack the normal text selecting. So even if you manage to highlight text with Textmarker (for example in the filename in a GDocs page) and attach a note, on reload the highlight fails to load and so the note is missing.

What is the difference between needing a "text selection" and "hijack the normal text selecting"?
Yes, if you are more interested in notes than in highlighting then I recommend to use a notes addon (but why not using GDocs own features?).
Please note that a successful restoration of saved highlights on page reload depends on the page's content: It's impossible to save direct references to paragraphs across reload, since all HTML elements cease to exist on unload. Therefore Textmarker will save meta data describing the text's position in order to find the correct text passages for restoring your highlights (this is necessary, because a text can occur multiple times on a page). Therefore the restoration is very likely to fail on pages with changing content.

Textmarker's notes feature seems really popular which is why I will continue to improve/extend it. Having a better overview of which note belongs to which highlight and where your notes (and highlights) are on the page is something that many users asked for, so it's very likely I'll implement it one way or another. Notes that are independent of higlights is a different story, though. Textmarker is a text highlighter first of all and I don't see why one wouldn't just use an additional addon for notes to accomplish this - you mentioned OurStickys, and I'm sure there plenty of other notes extensions(?)

**Comment by hmijail** [comment]
>What is the difference between needing a "text selection" and "hijack the normal text selecting"?

Google Docs hijacking the "normal text selecting" means that when a Google Docs' document is loaded, text selection and contextual menus don't work as they normally do.

Anyway, I guess that this can be closed then.
