### ISSUE TITLE
[bug] Highlighted text hid changes in the underlying text

### ISSUE THREAD

**Issue by hmijail** [ufb/Textmarker#134]
**Describe the bug**
A text highlight got loaded on a newer version of the page. ... or maybe the page changed while it was loaded?? The new version of the underlying text (in which some words had been deleted) only appeared when I deleted the highlight.

**To Reproduce**
This happened on a README page in GitHub. I am not sure I can reproduce. 

**Expected behavior**
If the highlighted text is different to the underlying text, the highlighting should fail and notify instead of hiding the changes.

**Which OS, Firefox edition, Textmarker version**
macOS 10.15.3
FF 77
Textmarker 5.2.3

**Comment by ufb** [comment]
> A text highlight got loaded on a newer version of the page. ... or maybe the page changed while it was loaded?? The new version of the underlying text (in which some words had been deleted) only appeared when I deleted the highlight.

I've read this paragraph 3 or 4 times, but unfortunately I can't figure out what you mean.
Could you please rephrase the issue description? Sorry for the inconvenience

> If the highlighted text is different to the underlying text, the highlighting should fail and notify instead of hiding the changes.

Also this I don't understand. What do you mean by "underlying text"? There is nothing underlying a highlighted text and therefore also nothing that is being hidden.
If a saved highlight text can't be restored (either because the text doesn't exist anymore or because the text's "neighborhood" has changed since your last visit) Textmarker won't restore anything but notify you about the failure.

Please note that saving highlights is a feature that is meant for pages that don't change their content. You can read the explanation for that [in your previous issue](https://github.com/ufb/Textmarker/issues/133#issuecomment-642625038)

**Comment by hmijail** [comment]
> saving highlights is a feature that is meant for pages that don't change their content. 

Then I guess I misunderstood the use case and mine is different. Thank you.
