### ISSUE TITLE
Lost highlights and notes; some notes are not anchored to highlights.

### ISSUE THREAD

**Issue by hmijail** [ufb/Textmarker#135]
**Describe the bug**
A lot of highlights are still there, but some not.
Some of the notes have disappeared, not sure whether the lost or remaining ones are/were connected to lost/remaining highlights.
The sidebar shows only 4 notes, but the page shows more than that.

**To Reproduce**
No idea, not going to try.
Might be related to the page being loaded in 2 tabs at the same time?

**Expected behavior**
Not losing highlights nor notes.

**Screenshots**
![image](https://user-images.githubusercontent.com/4139546/84341644-f9343f00-abe6-11ea-9255-d41702353b1c.png)
Note how some notes in the page are not the ones in the sidebar.

**Which OS, Firefox edition, Textmarker version**
macOS 10.15.3
FF 77
Textmarker 5.2.3

**Additional context**
FWIW, OurStickys works all right in this same situation.

**Comment by ufb** [comment]
> Might be related to the page being loaded in 2 tabs at the same time?

Yes.
As explained in one of your previous issues Textmarker has to store meta infos about the position of a highlighted text in relation to its surrounding, because DOM elements ceise to exist on page unload. The highlight's position/surrounding can also include other highlights (as in your screenshot), so if you use 2 tabs for the same page there is no way Textmarker can save correct infos about the surrounding. One example:
You have a paragraph with the following text:

> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 

In tab 1 you highlight "Lorem ipsum dolor sit amet" and in tab 2 you highlight "sed diam nonumy eirmod tempor":
The meta infos for highlight 1 will include that it is in the first (text-)node of a paragraph (i.e. a **p** element). The meta infos for highlight 2 will inculde the same.
On reload Textmarker might restore highlight 1 correctly but fail for highlight 2, because it's looking for the first node in **p**, which is now highlight 1.

> FWIW, OurStickys works all right in this same situation.

It's not comparable. Textmarker's notes are related to highlights.

**Comment by hmijail** [comment]
Note that even though I had 2 tabs open at the same time, one of them was idle. So it's not like I made changes in both at the same time.

Anyway, as mentioned elsewhere, I guess it's just that my use case is different. Thank you.

**Comment by ufb** [comment]
> Note that even though I had 2 tabs open at the same time, one of them was idle. So it's not like I made changes in both at the same time.

Completely idle? So you didn't do any changes at all on one tab? It's not about making changes at the  same time, but since Textmarker identifies your history entries by the page's URL the restoration will also fail (and has to fail) if you make changes in both tabs if you don't update the idle tab (by reloading it) before doing a change there.

**Comment by hmijail** [comment]
Yes, the 2nd tab was opened in a different window in another monitor and I forgot about it while I made new highlights and notes in the first window.

**Comment by ufb** [comment]
OK, thx for taking the time to report this!
