### ISSUE TITLE
not work properly on Firefox 62.0

### ISSUE THREAD

**Issue by I-RaFaEl-I** [ufb/Textmarker#19]
The highlighter app work but not able to access any menu, change highlighter colors ether

**Comment by ufb** [comment]
hi I-RaFaEl-I,
by "menu" you mean the dropdown menu when you click on the Textmarker icon in the navigation bar?
I got Firefox 62 and everything is working fine, can you add some more details please:
- Which OS (Windows, MacOS or Linux)
- Which Textmarker version
- Are there any error logs (either on Textmarker's error logs page or in the browser console when trying to use the menu -> you can open the browser console using Ctrl + Shift + J on non-MacOS)
- Was it working for you with Firefox 61?
Thx, I will look into it tomorrow then ;-]

**Comment by I-RaFaEl-I** [comment]
Some screenshots:
### Drop menu
![pic2](https://user-images.githubusercontent.com/7343817/45691086-78cdd080-bb1d-11e8-89dd-14b8fd42c4bd.JPG)
### Setting menu
![pic1](https://user-images.githubusercontent.com/7343817/45691089-79666700-bb1d-11e8-9291-be89c8b15103.jpg)

No of them show me anything when i click into, exept "Pause/Resume Textmaker" its the only one that seems to be woking fine,  it actually Pause and Resume Textmaker :+1: 

* Windows 8.1
* Textmarker 3.8.2
* no error logs
* I don't know :S , I just try Textmarker after Firefox updating :D

**Comment by ufb** [comment]
Hey, I created new Firefox profiles on 4 different machines (Linux, MacOS and 2x Windows) and installed Textmarker on them - menus were working just fine.

@I-RaFaEl-I What you could try is to also create a new Firefox profile on your Win8 and check if Textmarker's menus are working on it -> if it does work then the course for the malfunction could be a different addon or a Firefox bug and  you can try the following on your default Firefox profile:
- uninstall Textmarker and install it again or...
- use a new Firefox profile (this is a rather drastical solution but maybe you can sync your current profile to it)

Here is how you create a new profile:
- close Firefox
- press Windows key and R at the same time
- then follow the instructions in the modal that pops up
It's quite easy and you can find the instructions [here](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_start-the-profile-manager-when-firefox-is-closed)

Unfortunately there is nothing more I can do, because I'd have to be able to reproduce the error, but this wasn't possible.
Best wishes!
