### ISSUE TITLE
It would be grate to name History items using highlighted words automatically.

### ISSUE THREAD

**Issue by eu21** [ufb/Textmarker#21]
Feature request: I need automatic naming of new History items be done by using a highlighted word. Right now we can can choose between Page title as a name or Date as a name.
Use case: huge army of foreign language learners.

### Settings -> History

**Saving to Textmarker history:**

- true Save changes automatically
- false Save changes manually 

**How would you like to name your history entries?**

- false By current date
- false By page's title
- false Use custom name
- true By using a highlighted word (It allows multiple items for one URL)

**Comment by ufb** [comment]
@eu21 Theoretically no problem.
Can you explain what exactly you have in mind? In particular, what do you mean by
- > using a highlighted word
- > It allows multiple items for one URL

Do you mean you'd like to choose one or more highlighted text passages to serve as entry name ~> i.e. "word1 word2 word3"? This would be complicated to accomplish, since the user has to somehow indicate which highlights to take.
Alternatively you could also combine automatic save + custom name

**Comment by eu21** [comment]
@ufb What I want to see in History is

- word1
- word2
- word3

Even if all of them are from one Article (Internet page). They certainly don't have to be combined in one long name " word1 word2 word3". I don't want to mix them. All I need from this extension is to be able to create clickable list of new words. Links should point me to the full context, the page I discovered new words. There will be duplicate links in History, but let's optimize later. I don't see duplicate links as a problem at all. It's a trade off I willingly accept.

Yes, I am already using combination of "automatic save + custom name" but

1. It forces me to enter the word manually, and this is not bad(The more you type new word the better you remember, but for native speakers It is annoying(not for me though))
2. It does not create new History item if there was another highlighted word from the same article. And this is a real problem, because I can not see clickable list of more that one new word per Internet page (URL, article).

**Comment by ufb** [comment]
Ah, alright, now I see, you would like to be able so create multiple entries for the same page, one entry per highlighted word.
This would require deep conceptual changes, because currently Textmarker identifies different entries by their URL and if a visited page's URL matches an entry it will restore all highlights using a certain algorithm. Each highlight has some meta data saved to it for being able to indirectly find the right text passages again (the text itself is not enough, since it could occur multiple times on the page). And the order in which the highlights have been made matters, since it is possible to do multiple highlights within one paragraph and even overlap or encapsulate them.
If you'd only use the option "one entry per highlight with entry name = highlighted word" then it wouldn't be a big problem, I guess (besides a lot of code changes for allowing for multiple entries per URL). But imagine for example following szenario (just skip the next block if you are not interested in technical considerations ;)

A user is saving multiple highlights on a page into one entry (1) (i.e. with option "name by page's tile"), then is switching to "one entry per highlight", saves a word on that same page to a second entry (2), then switches back and adds some more highlights to the first entry (1) (still for the same page). This would create a big mess: Revisiting aforesaid page Textmarker would have to restore both the highlights of entry 1 and entry 2 whereas order of the highlights matters (see above). But if it just restores the highlights of the first entry (1) first, then the single highlight of the second entry (2), the algorithm is likely to break, because some highlights from entry 1 have been made before the one of entry 2, some others later on.
A walkaround could be to only allow one option per URL (either one entry per highlight OR one of the other saving options), but you see it's not at all a trivial problem to deal with. The szenario might be farfetched, but it's only one example of what could go wrong and I have to consider all unlikely cases.

But I will think about it if there is a way to accomplish your goal without having to reinvent the whole extension;-] -> will keep you up-to-date here...

A quick note on duplicate names:
Duplicate history entry names are already dealt with in Textmarker: word, word(2), word(3), ... . So no problem there

**Comment by ufb** [comment]
@eu21 Quick question:
The easiest way to accomplish your goal without having to change half the code would be the following:
- A one-highlight-per-entry option which can be enabled as an alternative to the other naming options

This way it would be no problem allowing for multiple entries for the same URL -> if you visit the page the highlights will be restored in chronological order and everytime you do another highlight Textmarker will save it in a different history entry.
In particular, it won't be possible to use both one-highlight-per-entry and name-by-title/date/manually for the same URL.

Would this be fine with you?

**Comment by ufb** [comment]
@eu21 as good as done. some more testing before releasing 3.9.0 in a few days or so
