### ISSUE TITLE
Shortcut problems

### ISSUE THREAD

**Issue by unpack5** [ufb/Textmarker#45]
I believe I was once able to use my "0" custom highlighter by pressing "0".

Now that doesnt work. At Shortcuts, next to "Custom Marker" I have "?" and key combinations with "?". If I switch between them, I get something like "unexpected error: unable to save configuration".

**Comment by ufb** [comment]
Yes, it's a bug in 4.0.0
Will get fixed asap

**Comment by ufb** [comment]
@unpack5 Can you confirm that it's the following 2 things that don't work?:
1) Using custom marker shortcuts
2) In settings > shortcuts: Trying to change the shortcut settings for custom markers results in error notification

And can you check if adding a new marker works for you and if you can use them via sidebar (instead of using the shortcut)?
Thank you

**Comment by ufb** [comment]
[fixed](https://github.com/ufb/Textmarker/commit/d94abb354b4df0b607ea61e26f5e4c3f214798fe)
fix will be added to next version (coming soon this week)

**Comment by unpack5** [comment]
I can confirm those two things.

I can add new custom markers and they can be selected in the sidebar.

Thanks for the fix!

**Comment by ufb** [comment]
uploaded version 4.0.1 with a fix

**Comment by unpack5** [comment]
Confirmed, works.
