### ISSUE TITLE
Enable user-defined key shortcut for pausing/starting Textmarker

### ISSUE THREAD

**Issue by unpack5** [ufb/Textmarker#46]

**Comment by ufb** [comment]
What would be the advantage to using the pause/start button from the navigationbar menu for this? Its just 2 clicks, 1 for opening the menu, another one for pausing/starting.
In case I implement a user-defined key shortcut -> would P+? make sense to you (i.e. P+Ctrl or P+Shift+Alt)? Textmarker is already cluttered with shortcuts, so the default state must definately be "disabled"

**Comment by unpack5** [comment]
Im okay with Ctrl+P. It would be useful because, at least for me, the whole process takes 3-5 seconds, and I need to switch often if I use the automatic highlighting.

**Comment by ufb** [comment]
OK, makes sense

**Comment by unpack5** [comment]
Another idea, maybe better and won't clutter the key space: add a Textmarker pause/resume button on the toolbar separate from the present button, which can be optionally added or removed by editing the toolbar.

**Comment by ufb** [comment]
Good idea, but I don't want to burden the user with 2 buttons just for this addon - some users don't know that they can remove them.
Will add the shortcut to upcoming version 4.1.0

**Comment by ufb** [comment]
Hi @unpack5 , there is a problem with the implementation:
Sor far all of Textmarker's shortcuts are used in the content script that gets injected to a website. In case Textmarker is paused all event handlers are being unregistered. So, once you use the shortcut for pausing Textmarker (let's say Alt+P), Textmarker is paused and therefore you cannot use Alt+P anymore for starting Textmarker.
There is an API for commands that would be a way around this, but which I don't use, because this only lets you set a default and fixed shortcut. So I could set it to Alt+P and the user won't be able to change it.
Maybe I will come up with a solution, but both alternatives a) keeping registered event handlers on websites, even though Textmarker was paused and b) using a fixed immutable shortcut are not good options in my point of view.

**Comment by ufb** [comment]
Also, I think a extension can only add one button to the toolbar/navigationbar.
But what do you think about a setting option that enables you to turn this button into an on/off toggle rather than a dropdown menu opener?

**Comment by unpack5** [comment]
I see. I think turning it into an no/off button is a good idea! The drop-down menu could still be displayed via right-clicking.

**Comment by ufb** [comment]
I don't think the menu-on-right-click is supported by the API. But you can convert it any time again thru the settings

**Comment by ufb** [comment]
Maybe the best way would be to have both simultaneously: Enable off/on switch via settings and if you click the button it will toggle Textmarker (pause/start) and also toggle the menu

**Comment by unpack5** [comment]
It sounds good, not sure exactly about how well it will work out, but we shall try it out.

**Comment by ufb** [comment]
Unfortunately the registration of a click handler is only supported if dropdown menu is disabled ([see here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setPopup)).

New setting option added on page Settings > Misc: Toolbar button can EITHER be used as toggle button to pause/start Textmarker OR for displaying the dropdown menu.
[git commit link](https://github.com/ufb/Textmarker/commit/4e7e1cd190566babb3164d4883d28a0cf7e7ce19)

Will be part of 4.1.0, coming soon

**Comment by ufb** [comment]
published
