### ISSUE TITLE
Feature request: a dark mode for the sidebar

### ISSUE THREAD

**Issue by klint** [ufb/Textmarker#51]
Hi
For visual consiste,ncy with the dark theme of Firefox, could there be a dark theme for Textmarker's sidebar as well? Thanks

**Comment by ufb** [comment]
Hello,

I did some research on your question and it seems that the Firefox developers still haven't extended their dark theme to apply for menus, sidebars etc. I recommend to address your question in a Firefox forum.

Maybe there are theme addons that fill this gap. You could also try ShadowFox (github.com/overdodactyl/ShadowFox), that supposedly does just that - haven't tried it out myself though.

In case that neither there is a fitting tool nor Firefox improves the dark theme soon I might think about implementing it for Textmarker - can't promise it though and it won't be in the next months, since just now I released a new major version and a bunch of fix-versions and I don't want to bother the users with too many updates in a short amount of time

**Comment by ufb** [comment]
Added dark theme - will be available in next release:
![dark-theme](https://user-images.githubusercontent.com/17272252/57582470-c0daa280-74b4-11e9-9e81-3cd91e6fe750.jpg)
Note: Theme has to be set manually, since there doesn't seem to be any programmatical option to hook onto user's theme change, unless it's a non-built-in theme.

**Comment by ufb** [comment]
![themes](https://user-images.githubusercontent.com/17272252/58728442-6f984180-83d6-11e9-9e40-b3ae691dbb55.jpg)

**Comment by ufb** [comment]
released 5.0.0 just now - darks themes now available

**Comment by gofraidh** [comment]
Hello, I'll post this here. I have trouble locating this setting. Can you please describe how to access it?

I also have an issue when I pause Textmarker, picture on top is unpaused, picture below is paused. As you can see, while in dark theme, the icon is not visible if Textmarker is paused. I thought this could be solved by changing the theme in Textmarker as above but I can't access the setting. It could also be a separate issue.

Running (Icon is visible)
![image](https://user-images.githubusercontent.com/7356171/60739243-1ed9b280-9f59-11e9-889b-ec4c539edbe2.png)

Paused (Icon disappeared) 
![image](https://user-images.githubusercontent.com/7356171/60739249-2a2cde00-9f59-11e9-8e79-cae46fa47812.png)

Thank you.

**Comment by ufb** [comment]
Hi gofraidh,

@dark theme:
the dark theme is just for Textmarker's sidebar. So if you don't use the sidebar you won't need this theme ;) You can open Textmarker's sidebar the same way you open other sidebars (i.e. bookmarks) -> in Firefox menu: View -> Sidebar -> Textmarker. Or you can right-click on any website and in Textmarker's context sub-menu choose "Open sidebar". In the sidebar you can change its theme at the very bottom.

@icon: In my browsers the icon looks as follows on pause:

![iconoff](https://user-images.githubusercontent.com/17272252/60739850-b5ab6c80-9f63-11e9-810c-655adc4744a4.jpg)

Which browser edition do you use (Regular Firefox, Developer Edition, Nightly, Android, ...)
Which OS (Windows10, Windows7, Ubuntu, Debian, MacOS, Android, ...)
Which dark theme (Firefox' built-in dark theme, ...)?

**Comment by gofraidh** [comment]
Hi ufb,
Thank you for prompt reply.

@dark theme: I am sorry ~facepalm~ I didn't notice this relates to sidebar only.

@ICON:  I had to wait to have an access to the computer where it occurs to test this again. I've discovered that it only occurs on this particular device while my other device shows the icon as indicated in your screenshot.

Which browser edition: 67.0.4 (64-bit) Firefox Quantum (Regular Firefox)
Which OS: Windows 10 Education
Dark theme: Firefox' built-in dark theme
