### ISSUE TITLE
Private browsing

### ISSUE THREAD

**Issue by HRussellZFAC023** [ufb/Textmarker#53]
Fresh install on beta channels has only a subset of features unless it is enabled for private tabs, perhaps put a note on the extensions page.
Many thanks!

Confirmed features not working without enabling it in settings:
* sticky notes
* changing settings and markers

New users should click this box:
![image](https://user-images.githubusercontent.com/22746105/54358272-d4ee5900-4657-11e9-8d4e-3577bdadb308.png)

**Comment by ufb** [comment]
Thank you for the hint!
Do the sticky notes and changing the settings work when `Run in Private Windows` is set to `Allowed`?
I've received an e-mail from Mozilla saying that

> starting with FF 67 (currently in the Nightly release channel)

 the whole extension will be disabled if this setting isn't set to `Allowed`.
Just now I tested it using a fresh profile with FF Nightly and when installing Textmarker the following notification was being displayed:
![priv-allow](https://user-images.githubusercontent.com/17272252/54360451-2cdf8c80-4665-11e9-8dae-f8d6f77c627a.jpg)
Also there was a more general notification:
![priv-allow2](https://user-images.githubusercontent.com/17272252/54360488-3ff25c80-4665-11e9-9ded-05efd981e34d.jpg)

If with FF 67 Textmarker is being disabled if not allowed by the user in private windows, then I think there is nothing to do for me, since the user will have this issue with any extensions and Firefox will make sure to let the user know about it.
But it seems that this is not the behavior you observed, since you were still able to use Textmarker - even though limited?

**Comment by ufb** [comment]
Update: Restarted my default FF profile and it updated to version 67. All my extensions were allowed in private windows by default. Changing this setting for Textmarker disabled the whole extension.

**Comment by HRussellZFAC023** [comment]
I installed a fresh version of Firefox  (67.0b) and the issue seems to have gone now, the extension seems to work properly even without the option enabled which is very confusing.
I am closing this issue, but re-open it if any one else experiences a similar thing.
Thanks for looking into this!
