### ISSUE TITLE
Hello, why was it deleted from firefox addon website?

### ISSUE THREAD

**Issue by minshifu** [ufb/Textmarker#56]
### What happened? Upset!

**Comment by ufb** [comment]
It hasn't been deleted; I've set the extension's status to `invisible`, because Mozilla refuses to take any action against user reviews that strongly violate against the review guidelines. Even after several weeks reviews containing insults and false statements haven't been removed and all my efforts getting in contact with Mozilla's addon team have come to nothing.
As for now I put the development of Textmarker on hold, but I still have hope to find a way to get in contact with Mozilla. It's possible though that I will delete Textmarker and self-host it instead. But I will do my best to not letting down the users.

**Comment by minshifu** [comment]
So sad. The Mozilla team should be more responsive.  Look forward to the revival of your addon.

**Comment by IslamSalah** [comment]
So sad about this...

**Comment by ufb** [comment]
Enabled Textmarker just now, because the review with the insults finally has been removed. Unfortunately Textmarker lost the status "Featured Extension" during its temporary deactivation. I will keep the extension enabled till I've decided to either continue hosting it via Mozilla or self-host it on GitHub.

**Comment by minshifu** [comment]
Great!
