### ISSUE TITLE
About "create folder" function 

### ISSUE THREAD

**Issue by minshifu** [ufb/Textmarker#57]
Hello, I have posted comments on the firefox adds-on page. Still wondering if you could add "create folder" function to help users better sort out saved history. Also, could you please let users set and change local directory for saved history?

As for Wired-Marker, it is an addon working under pre-quantum firefox versions similar to Textmarker in many ways. Here is its official website:  http://www.wired-marker.org/en/    If possible, you may refer to it to make improvements on Textmarker. 

 Thank you for your work and best regards!

**Comment by ufb** [comment]
Hi minshifu,
thank you for opening this issue, this way it's easier to communicate - and also to let other users participate.
Please understand that I'm currently very busy and won't have much time to implement new features. As soon as I find the time there are important things on the Textmarker todo list already, like bug fixes etc.
My comments and questions below:

> Still wondering if you could add "create folder" function to help users better sort out saved history.

The history works with tags (instead of folders). You can add tags to each history entry and filter your entries by tag names; this has the same effect as opening a folder - instead of putting your entries in folder "someFolderName" just add the tag "someFolderName" to those entries. You can then filter your entries by tag name - which is equivalent to opening a folder.
Can you explain how a folder system would be an improvement? If there are good reasons for giving preference to folders over tags that I just haven't acknowledged yet, I might find the time to implement a folder system.
![tags](https://user-images.githubusercontent.com/17272252/55673552-e8789280-5898-11e9-9a7f-30fcdd1403f9.jpg)

> Also, could you please let users set and change local directory for saved history?

Can you explain what exactly you mean by that (sorry for my obtuseness^^)? Textmarker uses the[ built-in storage API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage), which saves your data in your Firefox profile folder. I cannot change that. Or do you mean the location for when you download a backup file? In this case it's completely up to you where you save it to ;)

>  If possible, you may refer to it to make improvements on Textmarker.

WiredMarker is a legacy extension, it won't work on my Firefox version. Also, I tried it out some years ago and really didn't like it at all.

> I have posted comments on the firefox adds-on page.

To be honest: I don't understand why so many users down-rate the addon in order to ask for new features - if you want the developer to do you a favor, then it's not the best approach to decrease the extension's overall rating. You probably didn't intend to, but that's how it comes across - no hard feelings though, just curious ;)

> Thank you for your work and best regards!

Thank you, I really appreciate it!

**Comment by ufb** [comment]
This post doesn't seem to be of anyone's interest (including its author) and will be therefore closed by next week.

**Comment by minshifu** [comment]
Sorry，I have been very preoccupied recently. Thank you for your explanation.

**Comment by ufb** [comment]
> I have been very preoccupied recently.

No worries, same here ;)
