### ISSUE TITLE
Turned off by rightclicking menu bar icon, cant turn on again?

### ISSUE THREAD

**Issue by piecevcake** [ufb/Textmarker#59]
I think you used to be able to toggle by rightclick, seems to have disappeared, how to turn it on again?

Oh I found it-the play/pause arrow!

Instruction and troubleshooting entry in you manual please!

**Comment by ufb** [comment]
Hi piecevcake
Yes, I re-styled the dropdown menu. Will add it to the manual in next release

**Comment by ufb** [comment]
I decided to completely revise the manual and especially the troubleshooting section, because I learned that most users don't bother reading it.
Most likely I'm going to add a "Troubleshooting" link to the navigation bar's dropdown menu and fill the troubleshooting section with more details.

-> Won't be part of next release, but probably the one after that.

**Comment by piecevcake** [comment]
thanks :+1:

**Comment by ufb** [comment]
Labeled the pause/start button:
![pause-label](https://user-images.githubusercontent.com/17272252/58730232-06ff9380-83db-11e9-8cb9-f4b761389d94.jpg)

Think that should do the trick(?)
