### ISSUE TITLE
Can you change the font size in notes?

### ISSUE THREAD

**Issue by piecevcake** [ufb/Textmarker#61]
It is too small sometimes, sometimes ok - if can be changed, is it in the manual? if not- feature request pls

**Comment by ufb** [comment]
> too small sometimes, sometimes ok

The font-size of the note's textareas is set to 12px - so it's always the same size.
Could you supply us with some screenshots to show what you mean?
Thank you

**Comment by ufb** [comment]
I could add an option to customize the note's font size - either globally (all notes the same font size) or individually (change font-size directly on the page for a specific note).
But this is of low priority and won't be implemented for upcoming release.

**Comment by piecevcake** [comment]
Thanks for your interest ufb

On some web pages the text is huge, and you have to zoom out the page to read it properly - then the note text is too small...
![textmarker notes text too small on zoom out ■ Can you change the font size in notes_ · Issue @2019 05 25, 14_11_46](https://user-images.githubusercontent.com/32110576/58363381-5afc0b00-7ef7-11e9-962e-95eb0b37cb85.png)

here's an example where smaller text would be good - 
![x](https://user-images.githubusercontent.com/32110576/58363343-c0033100-7ef6-11e9-9f37-7752876ff3d1.png)

**Comment by ufb** [comment]
> On some web pages the text is huge, and you have to zoom out the page to read it properly - then the note text is too small...

Aaaah, alright. I was already questioning my senses, because... 

> It is too small sometimes, sometimes ok

... made me think, that Textmarker's notes show different font sizes.

I will probably add options for customizing the font (ie size) with some future version (ie the one after the next).
The easiest would be to have a settings option on Textmarker's settings page. This way you'd change the text size for ALL notes. Nicer would be to be able to change it for each note individually, but this takes more time, since it involves a design part as well -> clicking on the gear icon to the right of a note opens the color selection - a text size select could be added there.

The next version will be released sometime in June, so this feature will have to be postponed for at least a couple of months. But maybe other users will drop some suggestion here as well ;)

**Comment by ufb** [comment]
Added feature: Customize font size of sticky notes:
![notefontsize](https://user-images.githubusercontent.com/17272252/58715751-094ff680-83b7-11e9-811d-b618409d6834.jpg)
Current font size setting will apply to all new notes.
Textmarker will remember the font size for each individual note.
Defaults to 12 pixels

Feature will be included in next version (probably by end of June).

**Comment by ufb** [comment]
5.0.0 has been released just now - font size is customizable (see screenshot above)
