### ISSUE TITLE
Notes: appearance & vertical resizing

### ISSUE THREAD

**Issue by piecevcake** [ufb/Textmarker#62]
Is it possible to have the note resizeable to 1 line, 1 cm wide, remove the header part and put the drag to reposition the note in another small box (or even put colour/close/move/resize into a right click menu when right click on the note)?  Sometimes just want to fit 1 word note in between 2 lines.

Thanks for very useful addon!

**Comment by ufb** [comment]
> Is it possible to have the note resizeable to 1 line, 1 cm wide

You can resize it horizontally to any size you wish - Textmarker will remember the note's dimensions. Currently the minimum height is 300px, which is a relic of when I first introduced notes. Will take it out for next release, so that you can resize it in any direction.

> remove the header part and put the drag to reposition the note in another small box (or even put colour/close/move/resize into a right click menu when right click on the note)

If I understand you correctly you'd like to have the header and action buttons not take any (or less) space? What do you think about only showing those elements when hovering over the note, would that be a good solution? Using a context menu (right-click) is not a good option in my opinion, because it wouldn't be self-explanatory to most users.

**Comment by ufb** [comment]
Committed some changes.
Minimum height is 3em now -> first text line:
![minnote2](https://user-images.githubusercontent.com/17272252/57982216-b62e8900-7a31-11e9-90fa-b13c98e565d9.jpg)

Header and action icons are hidden until hovering over the note:
![minnote1](https://user-images.githubusercontent.com/17272252/57982223-cc3c4980-7a31-11e9-85ca-2a3aa30fb13d.jpg)

You can change the note's dimensions as you please; Textmarker will remember them (as was the case already):
![minnote3](https://user-images.githubusercontent.com/17272252/57982234-ed049f00-7a31-11e9-821f-0045de6c7a0b.jpg)

These changes will be available with next release (probably June). Feel free to give feedback before.

**Comment by ufb** [comment]
> Header and action icons are hidden until hovering over the note

Made this behavior optional. Default: off.

![notes-tab](https://user-images.githubusercontent.com/17272252/58174542-af9c4d80-7c8d-11e9-960e-bcb8aef61040.jpg)

**Comment by piecevcake** [comment]
Thanks - brilliant!

Size - possible to get the note to fite between the lines? like this (annotation on screenshot)?
![x](https://user-images.githubusercontent.com/32110576/58363092-37cf5c80-7ef3-11e9-9ce3-d6e049165e14.png)


Or maybe displace text-like pagemarker?
![x1](https://user-images.githubusercontent.com/32110576/58363098-56355800-7ef3-11e9-9c45-6bac57a5be0d.png)

**Comment by ufb** [comment]
> Size - possible to get the note to fite between the lines?

Not really. Looks OK in your screenshot - but only because there is plenty of space between the lines. But Textmarker can be used on any website - including sites with narrow line-heights.

> Or maybe displace text-like pagemarker?

I like this better, even though there is a similar problem with spacing -> compare [my answer to your other issue](https://github.com/ufb/Textmarker/issues/63?_pjax=%23js-repo-pjax-container#issuecomment-495921066).
