### ISSUE TITLE
Notes: Arrows pointing to corresponding highlight

### ISSUE THREAD

**Issue by piecevcake** [ufb/Textmarker#63]
something like this maybe?
![x](https://user-images.githubusercontent.com/32110576/57820004-082ba080-77df-11e9-8bd5-5eaf9f1e67cc.png)

**Comment by ufb** [comment]
Sorry, can you provide some explanation of what exatly this feature request is about? From the image I can only do a wild guess:
It seems that you'd like Textmarker's sticky notes to have an arrow pointing to the corrsponding highlight?

**Comment by piecevcake** [comment]
Yes that's right :)

**Comment by ufb** [comment]
This is way too much work.
Of course it's easyly done in your image editor, but on an HTML page... there are tons of things and edge cases to consider - let alone all the design considerations and implementations.
I could display a small note icon at the corresp. highlight, as you suggested [here](https://github.com/ufb/Textmarker/issues/62#issuecomment-495825398), if I understood you correctly:

![noteicon](https://user-images.githubusercontent.com/17272252/58370326-9517dd80-7ef4-11e9-9135-653e62e74044.jpg)


But even that is not straight-forward, since it will overlap with portions of the text.

Cerntainly it's not something I'm going to implement for upcoming release, but I will leave this post open for now and maybe other users come up with suggestions as well...

What you can do for now is moving your notes to the place that suits you. And with next release you can [resize them vertically down to 1 text line and even hide the heading and icons, until you hover over them](https://github.com/ufb/Textmarker/issues/62):

![minnote](https://user-images.githubusercontent.com/17272252/58370455-3c494480-7ef6-11e9-9431-1856afe741fa.jpg)
