### ISSUE TITLE
What exactly is Syncing, synced storage?

### ISSUE THREAD

**Issue by strawbeard** [ufb/Textmarker#65]
Manual tab (v.4.4.0) contains no description of the terms _Syncing_ and _synced storage_. The Syncing tab offers no help either. Please explain.

Second question: Can you confirm that the shown slider switch state
<img width="45" alt="Firefox000" src="https://user-images.githubusercontent.com/4041932/58571828-d123a900-823a-11e9-83cc-d07fd338d5ac.png"> 
means **OFF** (O)?

I'm just beginning to use Textmarker.

**Comment by ufb** [comment]
Hi strawbeard,

> Can you confirm that the shown slider switch state means OFF (O)?

Yes

> Manual tab (v.4.4.0) contains no description of the terms Syncing and synced storage.

I haven't explained those terms, because syncing is part of the browser, not Textmarker. Syncing means that you have a Firefox account, log into this account from different Firefox profiles (i.e. on different devices) and sync those profiles - which means that things like bookmarks, addons etc. will be the same in both profiles: When you add a bookmark in profile A and profile A is being synced to profile B then also profile B has this bookmark. You can learn more about syncing [here: https://support.mozilla.org/en-US/kb/how-do-i-set-sync-my-computer](https://support.mozilla.org/en-US/kb/how-do-i-set-sync-my-computer).
In case of addons (i.e. Textmarker) it means the addons are the same in both profiles.
Addons merely have the choice to either store data into your local or synced storage - or both. Textmarker lets the user decide. So you can save your data (settings and highlights(=history)) to the synced or the local storage.
When you opt into syncing on Textmarker's Syncing tab without having a Firefox account to be able to sync then this feature won't work.

Hope this clarifies things

> I'm just beginning to use Textmarker.

:) Best wishes
PS: A new version with some new features and bug fixes will be released next month

**Comment by strawbeard** [comment]
Hi ufb,

Thank you for the super-fast response.

> Hope this clarifies things

Oh yes, it really does;-) I do have a Firefox account and use it for syncing bookmarks, history and logins, but not add-ons. Maybe I must activate the add-on option to enable Textmarker's syncing.

**Comment by ufb** [comment]
> Maybe I must activate the add-on option to enable Textmarker's syncing
Yep ;)
