### ISSUE TITLE
New coming version 5: Problem of permissions?

### ISSUE THREAD

**Issue by DenB10** [ufb/Textmarker#67]
Hi ufb,

I started to translate strings for the new version 5, it remains only the manual and troubleshooting pages.

But I encounter problems to test furthermore:
First, I was not able to make any highlight. I've had to add the "content_scripts" part from the previous version in the manifest file. That's OK now.
But then, the highlights are not being restored at page reload. Note that they are present in the history and no notifications pop up.

Is this problem of permissions, in the Textmarker code?

**Comment by ufb** [comment]
> Is this problem of permissions, in the Textmarker code?
It pretty much sounds like it. You zipped the exention folder for testing, right? Using the `web-ext` tool for testing it everything worked fine, so I assume you are correct that it has something to do with the new permissions. Will test it asap..
I will be on a small trip now till Sunday. On Sunday I will have a look into it.
Thanks a lot :)

**Comment by DenB10** [comment]
> I will be on a small trip now till Sunday.

So, have a good trip! ;)

**Comment by ufb** [comment]
Just now I tested it with a zipped folder like this:
- I zipped the extension folder
- Opened the Firefox page `about:debugging`
- Loaded Temporary Addon
This will temporarily disable my current version of Textmarker.
My old higlights are being restored and I can create new highlighs, save and restore them.

How exactly did you proceed to test the new version?

**Comment by DenB10** [comment]
- I zip the extension folder content
- I backup my Firefox profile
- I install the .xpi file in Firefox
- I test
- I restore my Firefox profile

Either with your method or the mine one, my old history entries are available, I can create new highlights with the new vesion (present in the history) but no highlights are restored when I revisit the website :(

**Comment by ufb** [comment]
Ah OK, I will try it with the exact same procedure later on today. Hopefully I will be able to reproduce this malfunction.

**Comment by ufb** [comment]
Hey sorry, I'm still not sure how exactly you proceeded:
- What tool do you use for zipping?
- How do you make sure the zipped folder ends with '.xpi' - do you just name it this way, or rename it from '.zip' or '.7z' to '.xpi'?
- And most importantly: How do you install it in Firefox? The reason I ask is that actually unsigned xpi files will be rejected by Firefox - unless you use the developer edition of Firefox (I believe Nightly works too) and have `xpinstall.signatures.required` set to `false` on the `about:config` page.

I tried it for the FF developer edition with signatures required set to false and Textmarker 4.1.1 installed previously. Then just drag&drop the xpi file into Firefox and confirm the dialog that pops up and enable Textmarker for private browsing in the 2. dialog that pops up. My old highlights are being restored and I can create new ones, which are being restored as well.

So, with all the different ways of testing the new version I wasn't able to reproduce the non-restorability you experienced :/

**Comment by DenB10** [comment]
I don't understand!
I'm using 7zip for zipping: I create a .zip file that I rename to .xpi.
Then I install the extension in Firefox (I have of course `xpinstall.signatures.requiredxpinstall.signatures.required` set to `false`), I'm using the last version of Firefox 60 esr.

> enable Textmarker for private browsing in the 2. dialog that pops up

No such popup!!!

Note I have to add in the `manifest` the `content_scripts` (copied from previous version 4) to be able to create new highlights (otherwise I can't).  I save them, there are present in the history but it's impossible to restore them when I open the page later ( no notification appears, no highlights as well). For me, something in `content_scripts` is missing or something in the Firefox configuration!

Note also that Textmarker entry in the address bar is always disabled, why?

**Comment by ufb** [comment]
> I create a .zip file that I rename to .xpi.

Ah alright, was just wandering :)

> I'm using the last version of Firefox 60 esr

Oh, you are using FF ESR! Maybe that could be the reason - acutally I'm surprised Textmarker 4.1 is working on ESR. Last time I checked (probably last year) Textmarker was still incompatible with ESR, because for ESR the FF developers always lag behind with the newest changes (ESR is more for secure browsing, mainly used by IT admins etc. and not so much for newest features and extension API changes).
I will check the compatibility list for all WebExtension APIs I use with Textmarker to see which parts might be a problem for ESR 60...

> I have to add in the manifest the content_scripts (copied from previous version 4) to be able to create new highlights (otherwise I can't).

This is because of the code restructuring I did. Now in version 5 a background script is checking the URL of any tab and in case there is a history entry for this URL the script will send it to the content script (the one that is being injected programmatically in v.5).
So, when content script injections only work with the old `content_scripts` setting then it's the expected behavior that restoration won't even start. The question here is why the new way of handling content script injections doesn't work - and it's very likely because of ESR lacking some API implementation needed for Textmarker 5.
Thank you for these clarifications, I will download ESR to see myself via browser console what is happening..

**Comment by ufb** [comment]
Good news:
With this crucial info that you use ESR I was able to track down the problem pretty easily:
I installed ESR and found out that there is indeed a new usage of a WebExtensions API which hasn't been implemented in ESR (yet) - and luckily it's a minor thing that is not really needed for Textmarker to work:

Textmarker is listening for tab changes to detect URL changes and is using a filter parameter to only detect the relevant tab changes - but such a filter is not part of the ESR version of this tab API (yet), which is why the code breaks and no scripts are being injected.
After I removed this filter everything worked fine in ESR :)

So it's pretty fortunate you are using ESR, since otherwise I would have been able to fix v.5 for ESR users before the release (because I didn't even know that Textmarker finally works for ESR at all -> on the Addon page where you download Textmarker it still says: "Parts of the underlying WebExtensions API are not supported on Android and ESR."

**Comment by DenB10** [comment]
It's effectively good news!

I was using Firefox Developer Edition before, just to be able to test unsigned extensions (standard FF doesn't allow to set the `xpinstall.signatures.required` parameter) but there was too frequent updates in my opinion. 
So I fell back on ESR! This is the reason and now, I'm happy that helps you for Textmarker (with more work although, sorry).

**Comment by DenB10** [comment]
Yippee! That works fine now, thanks :)

**Comment by mehturt** [comment]
Sorry to comment on this closed ticket, but I'm using Firefox 60.7.1 ESR from Debian stretch repo, and Textmarker stopped working today for me (I guess after I restarted the browser), the addon menu like Settings, or Error logs does not open anything. Is TM 5.1.1 compatible with this FF release? Thanks.

**Comment by ufb** [comment]
@mehturt No need to apologize, I'm glad when users report issues here instead of writing ugly reviews;)
Until 10 days ago I thought Textmarker and ESR are still not compatible, that's why I have this note on the addon's page:

![esr2](https://user-images.githubusercontent.com/17272252/60958602-ecd4a180-a306-11e9-8409-3b8f1319e337.jpg)

After DenB10 told me that 4.1.1 was working on ESR I installed it myself and tested it. The new feature for copying highlights is not supported by ESR, but most things should work.
I experienced the same issue of Textmarker pages not opening after I temporarily installed a test version and then downgraded to 4.1.1 again. For me it helped to **uninstall Textmarker and re-install it** - and also to restart Firefox. Can you try that and let me know if that helped?
Thank you

**Comment by mehturt** [comment]
@ufb thanks. So I tried to reinstall 5.1.1 but it does not work, now even the icon does not appear in my toolbar. Did you mean to reinstall 4.1.1 as it should be compatible with ESR? I don't know how to do that, there does not seem to be an option to install an older release on addons.mozilla.org

**Comment by mehturt** [comment]
@ufb sorry, restarting FF and reinstalling again it now works.. thanks

**Comment by ufb** [comment]
Great :)

**Comment by ufb** [comment]
I have no idea what causes this problem, but good to know that good old method "restart & reinstall" worked for you :)
PS: Downgrading never is a good idea, that can cause unrecoverable problems - I think downgrading to 4.1.1 should be fine, but I cannot guarantee it.
