### ISSUE TITLE
Version 5.0.0 not highlighting in iFrames in FF 67.0.4 (64-bit)

### ISSUE THREAD

**Issue by aforsyth-nz** [ufb/Textmarker#74]
worked fine before today's update.

I have attempted fault resolution by:-
•	checking/unchecking boxes in settings>misc;
•	uninstalling/reinstalling;
•	downgrading to version 4.1.1 (that works).

**Comment by ufb** [comment]
> Version 5.0.0 not highlighting in iFrames

It was working for the iFrames i testest; can you please provide a URL? Then I can check if it's a bug.

> downgrading to version 4.1.1 (that works)

Oh, downgrading browser extensions never is a good idea, because we cannot assure backwards compatibility. I'm surprised this is working for you ;) Please contact me in case you upgrade again to v5 and something is broken.

**Comment by aforsyth-nz** [comment]
URL = http://customerzone.vodafone.co.nz/residential/inhome/tv/tvguide/tvg-grid.cfm
Marking works in lower iFrame under v4.1.1 but has stopped functioning in v5.0.0~5.0.2 when page display has been set to display "My Channels" 

![Annotation 2019-07-08 092329](https://user-images.githubusercontent.com/52516165/60774162-4355aa80-a164-11e9-9f80-c235767df9e2.jpg)
![Annotation 2019-07-05 132250](https://user-images.githubusercontent.com/52516165/60774163-46e93180-a164-11e9-9582-b4ad40824b50.jpg)


![Screenshot 2019-07-08 09 30 04](https://user-images.githubusercontent.com/52516165/60774143-05588680-a164-11e9-9c14-1349de27a70b.jpg)

**Comment by aforsyth-nz** [comment]
![1](https://user-images.githubusercontent.com/52516165/60774276-1c987380-a166-11e9-8563-2e846ba589c9.png)
![2](https://user-images.githubusercontent.com/52516165/60774277-1c987380-a166-11e9-9cb9-3e4936cc12f7.png)

**Comment by ufb** [comment]
Ah, thanks a lot for these details!
Just now I had a look into it and the problem seems the following:
When you can some settings (i.e. switching to "My Channels" or submitting a different time frame) the inner frames are getting reloaded.
Texmarker v5 is using programmatical script loading and is doing so by listening to URL changes of your tabs. But since the main URL of the current tab hasn't changed (only the ones of the inner frames), this script loading won't get triggered for the reloaded frames.
I will try to fix it tomorrow.
Thanks again for your help :)

**Comment by aforsyth-nz** [comment]
Many thanks @ufb, much appreciated. 
I was comparing the two manifest.json files & wasn't sure how to fix myself
![Annotation 2019-07-08 102849](https://user-images.githubusercontent.com/52516165/60774712-6dab6600-a16c-11e9-8cf4-7c4972012dbd.png)

**Comment by ufb** [comment]
Released 5.1.0 just now.

Permission **Access browser activity during navigation is mandatory** now.
Plese report if you still have issues with non-loading scripts!

I experimented with above cited page: Should work in sub-frames now. But please not the following:
  - Those pages seem to have frequently changing content, which will likely result in a restoration failure
  - Depending on your settings and filters the URL might slightly change, so a page that looks exactly like the one you saved highlights on may acutally have a different URL - hence no highlights.

PS: Content scripts are not being loaded thru the `content_scripts` field in the manifest, but programmatically. The user can opt-out of automatic injections (Settings > Misc).

[https://github.com/ufb/Textmarker/blob/master/src/background/modules/injection-manager.js](https://github.com/ufb/Textmarker/blob/master/src/background/modules/injection-manager.js)

**Comment by aforsyth-nz** [comment]
That seems to be working now thanks
