### ISSUE TITLE
Notes color setting now only affects header not the note

### ISSUE THREAD

**Issue by aforsyth-nz** [ufb/Textmarker#82]
Notes color setting now only affects header not the note
Happens regardless of Notes settings i.e  **_Semi-transparent if inactive_**
Previous versions would display the entire note in the selected color
![2019-07-09](https://user-images.githubusercontent.com/52516165/60881061-07703180-a299-11e9-8bac-fb4015265e73.png)

**Comment by ufb** [comment]
Hm, strange, Firefox' inspection tool suggests that the background gradient should be applied:

![textarea-gradient](https://user-images.githubusercontent.com/17272252/60883850-9b1b1100-a24b-11e9-857d-e05898100c43.jpg)

Found what is causing this: I've set the details option `cssOrigin` for inserting stylesheets to `user`, because of this:

![cssOrigin](https://user-images.githubusercontent.com/17272252/60884443-2e087b00-a24d-11e9-9e0c-cb53823ffcbd.jpg)

Thought this would mean that only the CSS asserted by Textmarker would apply, but guess I misunderstood the red-unerlined sentence(?)

Fix will be included in next version.

**Comment by ufb** [comment]
Fixed. Released. v5.1.1
