### ISSUE TITLE
Highlighted text on some pages can not be restored.

### ISSUE THREAD

**Issue by minshifu** [ufb/Textmarker#90]
How are you doing?  It is a pity that highlighted text on some pages can not be restored as shown by the pictures below. The highlight just disappeared after the page was refreshed.
Could you pls fix it? Thank you and best regards!

![图片](https://user-images.githubusercontent.com/5119952/64063634-5bf4b500-cc29-11e9-8cfb-a13ba9636f01.png)
![图片](https://user-images.githubusercontent.com/5119952/64063637-6020d280-cc29-11e9-872b-1c0bf164604b.png)

**Comment by ufb** [comment]
Hi, just checked this site and highlighted the same text and it got restored after reload.
Which OS are you using? And which Firefox? And the latest Textmarker version?
And can you please check Textmarker's error logs page for a hint on why the restoration failed? Thanks!
I'll have a look into this tomorrow or the day after

Best wishes

**Comment by minshifu** [comment]
> 
> 
> Hi, just checked this site and highlighted the same text and it got restored after reload.
> Which OS are you using? And which Firefox? And the latest Textmarker version?
> And can you please check Textmarker's error logs page for a hint on why the restoration failed? Thanks!
> I'll have a look into this tomorrow or the day after
> 
> Best wishes

Pls try this page https://www.voanews.com/international-edition   And pls do not select text in the first row of episodes. Pls click the blue "Show More" button at least once and select text from the second row of episodes as shown by the picture below. Then you will find the problem I mentioned.   Thank you!

![图片](https://user-images.githubusercontent.com/5119952/64063960-34541b80-cc2e-11e9-866a-bcb9a284cc74.png)

**Comment by ufb** [comment]
OK, I know now what the problem is:
After the site has been fully loaded Textmarker will try to restore your highlights - but the text to highlight isn't there yet, because it gets rendered programmatically when you click the button "Show More".
What you can do is the following:
a) Disable automatic restoration re-trial after 5 seconds (under Settings > History):
![no5s](https://user-images.githubusercontent.com/17272252/64064048-1e7a3280-cbfd-11e9-8170-043cda2e83fa.jpg)

b) Open the site. Textmarker will fail. Open Textmarker's sidebar. After you clicked the button (so when you see all the text that is supposed to be highlighted) click the retry button in the sidebar:
![retrybtn](https://user-images.githubusercontent.com/17272252/64064065-5b462980-cbfd-11e9-97b2-ea00dbdefbc1.jpg)

This retry option has been implemented for exactly this sort of szenarios - pages that render content programmatically after the document's loaded event happened ;)

**Comment by minshifu** [comment]
Thank you very much. It is solved. Have a nice day!
