### ISSUE TITLE
Cannot Restore Marked texts!

### ISSUE THREAD

**Issue by sghazagh** [ufb/Textmarker#93]
Hi,
I just try to use this add-on. Seems nice but cannot get it working to restore marked texts.
Seams that the text does not save as when I close and open the Firefox, the history page has not the saved text anymore. Initially the history page shows the text but clears it ater open/close of Firefox browser.
Json file is attached for your review.

[Textmarker-backup-10_15_2019__10_28_19___.json.txt](https://github.com/ufb/Textmarker/files/3726750/Textmarker-backup-10_15_2019__10_28_19___.json.txt)

(Using Firefox 69.0.3 x64)

**Comment by ufb** [comment]
Hi @sghazagh,
the restoration of your highlight failed, because the page was changing its content after the page's load event; your Textmarker's Error Logs page probably says something like: "Text found but doesn't match conditions". Textmarker treats this highlight as being "lost" now, because in your settings the following option is enabled: "If a highlight wasn't restorable: Don't try again next time."

Please try with unchecking 2 options under Settings>History, then highlight your text again on that page and see if it works:
![settings](https://user-images.githubusercontent.com/17272252/66844383-84810600-ef6e-11e9-8bbc-4ec0ef1058c5.jpg)
