### ISSUE TITLE
Enhancement: Give Focus to Note window

### ISSUE THREAD

**Issue by Ormek** [ufb/Textmarker#95]
After I created a note, I like to start typing immediatly. With Textmarker 5.1.2 I have to click the created Note first. So it is:
1. Select the Text
2. Create a Hightlight (M, click)
3. Create a Note
   1. Select the Highlight 
   2. Navigate through Context Menu to create Note
   3. _Click the Note_
4. Start typing.

With #94 I try to get rid of "Navigate through Context Menu to create Note".

**Comment by ufb** [comment]
Hi Ormek,
after creating a note via context menu Textmarker will set the focus on the newly created note, so that you can start writing without step 3.iii. Just now I tried it out and it worked just fine. Can you tell me in which environment this doesn't work for you - which OS (Windows7, Windows10, Linux, MacOS, Android, ...), which Firefox edition (Regular, Developer, Nightly, ESR, ...)?
Thank you
For avoiding too many steps for creating a note: see #94

**Comment by ufb** [comment]
Shortcut for adding notes is implemented (see #94 ), as well as autofocus on new note.
Will be part of next release
